name: becharkh

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: becharkh-app
    container_name: becharkh-app
    restart: unless-stopped
    working_dir: /var/www
    command: php-fpm
    volumes:
      - ./:/var/www
    env_file:
      - .env
    depends_on:
      - mongo
      - redis
    networks:
      - becharkh-network
      - music-network

  queue-worker:
    image: becharkh-app
    restart: unless-stopped
    working_dir: /var/www
    command: >
      php artisan queue:work --queue=becharkhsite,default --tries=3 --timeout=300 --max-jobs=200 --max-time=3600
    volumes:
      - ./:/var/www
    env_file:
      - .env
    depends_on:
      - app
    networks:
      - becharkh-network
      - music-network

  scheduler:
    image: becharkh-app
    container_name: becharkh-scheduler
    restart: unless-stopped
    working_dir: /var/www
    command: php artisan schedule:work
    volumes:
      - ./:/var/www
    env_file:
      - .env
    depends_on:
      - app
    networks:
      - becharkh-network
      - music-network

  nginx:
    image: nginx:1.31
    container_name: becharkh-nginx
    restart: unless-stopped
    ports:
      - "8006:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - becharkh-network

  mongo:
    image: mongo:8.0
    container_name: becharkh-mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${DB_MONGO_DATABASE}
    volumes:
      - becharkh_mongo_data:/data/db
    networks:
      - becharkh-network
      - music-network


  redis:
    image: redis:8.8
    container_name: becharkh-redis
    restart: unless-stopped
    volumes:
      - becharkh_redis_data:/data
    networks:
      - becharkh-network

networks:
  becharkh-network:
    driver: bridge
  music-network:
    external: true

volumes:
  becharkh_mongo_data:
  becharkh_redis_data:
